In [ ]:
# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [21]:
s="Hi there Sam!"
s=s.split()
print(s);


['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [23]:
planet="Earth"
diameter=12742
print('The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [24]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [9]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all even integers from 20 to 35")
print(array)

Array of all even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Pandas

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
import numpy as geek
arr1=geek.array([1,2,3])
arr2=geek.array([4,5,6])
gfg=geek.concatenate((arr1,arr2),axis=0)
print(gfg)

[1 2 3 4 5 6]


## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [1]:
data=[['Tom',10],['nick',15],['juli',14]]
df=pd.DataFrame(data,columns=['Name','Age'])

NameError: name 'pd' is not defined

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [12]:
import datetime
import pandas as pd
test_date=datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
K=5
date_generated=pd.date_range(test_date,periods=K)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023'], dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [13]:
import pandas as pd
lst=[['Geek',25],['is',30],['for',26],['Geeksforgeeks',22]]
df=pd.DataFrame(lst,columns=['Tag','number'])
print(df)

             Tag  number
0           Geek      25
1             is      30
2            for      26
3  Geeksforgeeks      22
